import type {NextPage} from 'next'
import Head from 'next/head'
import {createGlobalStyle} from 'styled-components'
import {COLORS} from '../constants'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GlobalStyles />
      <main>
        <h1>HELLO WORLD</h1>
      </main>
    </div>
  )
}

const GlobalStyles = createGlobalStyle`
  :root {
    --color-background: ${COLORS.dark.background};
    --color-text: ${COLORS.dark.text};

    box-sizing: border-box;
  }

  *,
  *::before,
  *::after {
    box-sizing: inherit;
  }

  html,
  body {
    padding: 0;
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
      Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;

    color: var(--color-text);
    background-color: var(--color-background);
  }

  a {
    color: inherit;
    text-decoration: none;
  }
`

export default Home
